name: Release

on:
  push:
    tags:
      - 'v*' # 匹配以'v'开头的tag

permissions:
  contents: write  # 给工作流写入仓库内容的权限

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史记录以访问所有tags  

      - name: .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Changelog
        id: Changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Zip
        run: |
          cd /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/publish/
          zip -r ../MFAWPF-${{ github.ref_name }}.zip *  

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/*.zip
          body: ${{ steps.Changelog.outputs.body }}
          draft: true
          prerelease: false