name: Release

on:
  push:
    tags:
      - 'v*' # 匹配以'v'开头的tag

permissions:
  contents: write  # 给工作流写入仓库内容的权限

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史记录以访问所有tags  

      - name: .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Changelog
        id: changelog
        run: |
          # 先安装git-cliff（假设已安装了Rust的包管理器Cargo），如果未安装Cargo，需要先安装Cargo
          cargo install git-cliff
          # 创建.gitcliff.toml配置文件（如果不存在）并写入配置内容，定义各类别对应的标题等规则
          cat << EOF >.gitcliff.toml
          [changelog]
          # 新增 | Feat 类别
          feat = "### 新增 | Feat"
          # 修复 | Fix 类别
          fix = "### 修复 | Fix"
          # 杂项 | Chore 类别
          chore = "### 杂项 | Chore"
          # 样式 | Style 类别
          style = "### 样式 | Style"
          # 重构 | Refactor 类别
          refactor = "### 重构 | Refactor"
          # 优化 | Perf 类别
          perf = "### 优化 | Perf"
          # 文档 | Docs 类别
          docs = "### 文档 | Docs"
          # 测试 | Test 类别
          test = "### 测试 | Test"
          EOF
          # 使用git-cliff生成变更日志，输出到CHANGELOG.md文件中，会根据配置文件的规则生成相应格式的内容
          git cliff -o CHANGELOG.md
          # 将生成的变更日志内容设置为工作流的输出，方便后续步骤使用
          echo "changelog=$(cat CHANGELOG.md)" >> $GITHUB_OUTPUT
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Zip
        run: |
          cd /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/publish/
          zip -r ../MFAWPF-${{ github.ref_name }}.zip *  

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/*.zip
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: false