name: Release

# 当推送以'v'开头的tag时触发工作流
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup.NET Core Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Changelog
        id: Changelog
        run: |
          python3 Tools/changelog_generator.py
          echo "::set-output name=generated_changelog::$(cat CHANGELOG.md)"  # 使用set-output输出变更日志内容
        env:
          DOTNET_ROOT: /home/runner/.dotnet
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Zip
        run: |
          cd /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/publish/
          zip -r ../MFAWPF-${{ github.ref_name }}.zip *  

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/*.zip
          body: ${{ steps.Changelog.outputs.generated_changelog }}
          draft: false
          prerelease: false