name: Release

on:  
  push:  
    tags:  
      - 'v*' # 匹配以'v'开头的tag

permissions:
  contents: write  # 给工作流写入仓库内容的权限
  
jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
        with:  
          fetch-depth: 0 # 获取完整历史记录以访问所有tags  

      - name: .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build 
        run: dotnet publish -c Release

      - name: Zip   
        run: |  
          cd /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/publish/
          zip -r ../MFAWPF-${{ github.ref_name }}.zip *  
          echo "Generated zip file:../MFAWPF-${{ github.ref_name }}.zip"
          
      - name: List files in publish directory
        run: |
         ls /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/*.zip
          changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'
