name: Release

# 当推送以'v'开头的tag时触发工作流
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  
          
      - name: Setup.NET Core Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Changelog
        id: Changelog
        run: |
          python3 Tools/changelog_generator.py  # 假设将Python代码保存为changelog_generator.py文件，并放在工作流执行目录下
        env:
          DOTNET_ROOT: /home/runner/.dotnet
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash
        # 设置输出环境变量，将Python脚本中保存的GENERATED_CHANGELOG环境变量输出，以便后续步骤使用
        outputs:
          generated_changelog: ${{ env.GENERATED_CHANGELOG }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Zip
        run: |
          cd /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/publish/
          zip -r ../MFAWPF-${{ github.ref_name }}.zip *  

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/MFAWPF/bin/AnyCPU/Release/win-x64/*.zip
          body: ${{ steps.Changelog.outputs.generated_changelog }}
          draft: false
          prerelease: false